### ISSUE TITLE
Up-to-date with React-Slick?

### ISSUE THREAD

**Issue by oyeanuj** [patricktran/react-magic-slider-dots#1]
Hey @patricktran! Thank you for creating this library, I had been looking for this sort of a solution.

Since this is derived from React-Slick and I currently use React-Slick, I was wondering if this is up-to-date with React Slick? In general, is that the plan or intention? 

Or would you recommend creating a fork of React-Slick, merging your changes and maintaining that for myself?

**Comment by patricktran** [comment]
Yes, this is up to date with React-Slick.  No need to fork.  Just add my npm package to your project.  I've reached out to the author @akirin of react-slick on the premise of merging my changes, but I never heard back from him...
