### ISSUE TITLE
Max number of visible dots not working

### ISSUE THREAD

**Issue by fuoridallarete** [patricktran/react-magic-slider-dots#13]
dots={dots} numDotsToShow={4} dotWidth={30}
it simply doesn't work
anyone had this issue?
can't find anything...
thanks x

**Comment by patricktran** [comment]
@fuoridallarete  Please check out the demo here: https://patricktran.github.io/react-magic-slider-dots/

You can copy and paste the code into your own project and it should work.  Let me know otherwise...
