### ISSUE TITLE
Doesn't work completely with infinite set to true

### ISSUE THREAD

**Issue by duongthienlee** [patricktran/react-magic-slider-dots#2]
Thank for your great lib.
It looks like react-magic-slider-dots doesn't handle infinite case.
Any ideas to handle that case ?

**Comment by patricktran** [comment]
Hi there.  Yes, the current version intends to mimic Instagram image galleries, where there is a start and end (not infinite).  Hopefully, no supporting the infinite case isn't a deal breaker for you... I'll keep this in mind and will put on the 'Wish List' for a near future release.

**Comment by patricktran** [comment]
@duongthienlee v1.1.3 supports the infinite use case.  Try it out!

**Comment by duongthienlee** [comment]
@patricktran. Thank for letting me know. Works like a charm !
